# Generated by Django 5.0.7 on 2024-07-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('time', models.TimeField(verbose_name='Time of Reservation')),
                ('count', models.IntegerField(verbose_name='Number of People')),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='Special Requests')),
            ],
        ),
    ]
